jobs:
  semgrep:
    container:
      image: returntocorp/semgrep
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    name: Scan
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      run: semgrep ci
name: Semgrep
on:
  repository_dispatch:
    types: trigger-ga___semgrep.yml
